CREATE TABLE THEATER (SNO INT, NAME VARCHAR(100), SEATING_CAPACITY INT);

INSERT INTO THEATER (SNO, NAME, seating_capacity, SCREENS) VALUES 
(1, 'SAKTHI', 450, 3),
(2, 'PVR', 250, 4),
(3, 'IMAX', 350, 2),(4, 'INOX', 150, 3),(2, 'ARRS', 550, 5);

SELECT * FROM THEATER;

ALTER TABLE THEATER ADD SCREENS INT;
ALTER TABLE THEATER ADD TYPE VARCHAR (10) DEFAULT "THEATERS";
ALTER TABLE THEATER DROP COLUMN TYPE;
DELETE FROM THEATER;